language: node_js
cache: yarn
node_js:
  - "10.16.0"
install:
  - yarn install
  - yarn cypress verify
  - yarn add --dev wait-on
script:
  - yarn start & wait-on http://localhost:8080 &
  - yarn test
  - kill $(jobs -p) || true
